blogTitle = "Kris Urbas: more than web developer"
blogDescription = "I help startups build their products"
blogImageUrl = "/static/img/profile-pic.jpg"
linkPrefix = ""
googleAnalyticsId = "UA-9904630-20"
