blogTitle = "Kris Urbas: more than web developer"
blogDescription = "I help startups build their internet products"
blogImageUrl = "/static/images/intro2.jpg"
linkPrefix = ""
hostname = "https://www.krisurbas.pl"
googleAnalyticsId = "UA-9904630-20"
